// Copies the canonical RBAC department map (apps/api/src/common/rbac/department-defaults.ts)
// verbatim into the web app (apps/web/src/rbac-departments.generated.ts) so the frontend and
// backend can never drift. Runs automatically on every web build (apps/web `prebuild`).
// Paths resolve from this script's own location — cwd-independent.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const src = join(root, 'apps/api/src/common/rbac/department-defaults.ts');
const out = join(root, 'apps/web/src/rbac-departments.generated.ts');

const banner =
  '// AUTO-GENERATED — DO NOT EDIT.\n' +
  '// Source of truth: apps/api/src/common/rbac/department-defaults.ts\n' +
  '// Regenerated by scripts/gen-rbac.mjs on every web build.\n\n';

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, banner + readFileSync(src, 'utf8'));
console.log('✓ RBAC department map synced → apps/web/src/rbac-departments.generated.ts');
